name: Create an issue
description: Creates a new issue using a template with front matter.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: alert-circle
  color: gray-dark
inputs:
  filename:
    description: The name of the file to use as the issue template
    default: .github/ISSUE_TEMPLATE.md
  check-duplicate:
    description: Check if issue already exists before creating one
    default: false
